title: 李珏颖
url: "https://rkrdudstar.github.io"
baseurl: "/resume-cn"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/rkrdudstar"
footer_text: "© 2025 李珏颖. 版权所有. 页面设计参考 Ankit Sultana"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "关于我"
    link: "/resume-cn"
  - name: "简历"
    link: "CV-CN.pdf.pdf"
  - name: "联系方式"
    link: "contact"
